######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 27 15:22:27 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
