######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 28 15:26:17 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
