#+STARTUP: logdone

* Configurations

** TODO Change passwords
Wait for Mail from IT. Change password if smartcard is there!


* Emacs

** TODO Add smart-mode-line to emacs config. 
** Language evaluation in org mode (see http://zeekat.nl/articles/making-emacs-work-for-me.html#sec-10)
** TODO Qt Auto complete


* Arbeitszeiten
- [2013-12-16 Sat 16:30]--[2013-12-16 Mon 18:00]
- [2013-12-18 Wed 17:30]--[2013-12-18 Wed 19:56]
- [2013-12-19 Thu 14:00]--[2013-12-19 Thu 17:02]
- [2014-01-05 Sun 14:30]--[2014-01-05 Sun 19:30]
- [2014-01-07 Tue 12:17]--[2014-01-07 Tue 14:00]
- [2014-01-09 Thu 12:15]--[2014-01-09 Thu 14:00]
- [2014-01-11 Sat 09:17]--[2014-02-11 Tue 13:15]
- [2014-01-12 Sun 13:25]--[2014-02-12 Wed 17:00]
- [2014-01-13 Mon 13:30]--[2014-01-13 Mon 15:15]
- [2014-01-16 Thu 14:15]--[2014-01-16 Thu 16:32]
- [2014-01-19 Sun 09:06]--[2014-01-19 Sun 13:00]
- [2014-01-20 Mon 16:58]--[2014-01-20 Mon 18:30]
- [2014-01-21 Tue 12:00]--[2014-01-21 Tue 13:55]
- [2014-01-23 Thu 12:15]--[2014-01-23 Thu 13:55]
- [2014-01-25 Sat 09:00]--[2014-01-25 Sat 14:00]
- [2014-01-27 Mon 10:21]--[2014-01-27 Mon 11:30]
- [2014-01-27 Mon 13:35]--[2014-01-27 Mon 15:40]
- [2014-01-28 Tue 14:44]--[2014-01-28 Tue 17:30]
- [2014-01-29 Wed 09:19]--[2014-01-29 Wed 12:25]


* Nuetzliches

** Gnuplot Befehle
Einen Ueberblick zu nuetzlichen Gnuplot Befehlen kann auf der folgenden Seite gefunden werden: http://people.duke.edu/~hpgavin/gnuplot.html

1. Um ein Data-file (zum Beispiel =*.epot*=) mit Gnuplot zu plotten, verwendet man: \\
   =gnuplot> plot "./argon.epot" using 1:2=. \\
   Hierbei wird die zweite Spalte gegen die erste Spalte aufgetragen. 
2. Dies kann auch mit mehreren Files gleichzeitig getan werden: \\
   =gnuplot> plot "./argon.etot" using 1:2, "./argon.ekin" using 1:2, "./argon.epot" using 1:2=
3. Um den Achsenabschnitt zu veraendern, verwendet man: \\
   =gnuplot> plot "./argon.epot" using 1:2; set yrange [-0.1: 2]=
4. Den urspruenglichen Achsenabschnitt kann man wie folgt wieder herstellen: \\
   =gnuplot> plot "./argon.epot" using 1:2; set autoscale=
5. Mit \\
   =gnuplot> replot= \\
   kann der Plot aktualisiert werden. 
6. Eine Uebersicht von =set= Befehlen: 
   Create a title:                  > =set title "Force-Deflection Data"== \\
   Put a label on the x-axis:       > =set xlabel "Deflection (meters)"== \\
   Put a label on the y-axis:       > =set ylabel "Force (kN)"== \\
   Change the x-axis range:         > =set xrange [0.001:0.005]= \\
   Change the y-axis range:         > =set yrange [20:500]= \\
   Have Gnuplot determine ranges:   > =set autoscale= \\
   Move the key:                    > =set key 0.01,100= \\
   Delete the key:                  > =unset key= \\ 
   Put a label on the plot:         > =set label "yield point" at 0.003, 260= \\
   Remove all labels:               > =unset label= \\
   Plot using log-axes:             > =set logscale= \\
   Plot using log-axes on y-axis:   > =unset logscale; set logscale y= \\
   Change the tic-marks:            > =set xtics (0.002,0.004,0.006,0.008)= \\
   Return to the default tics:      > =unset xtics; set xtics auto= \\ 
   Set output:                      > =set output 'introduction.png'== \\

   

* Aufgaben
** TODO Read online tutorial about Qt (signal, slots)
   DEADLINE: <2014-01-29 Wed> SCHEDULED: <2014-01-26 Sun>

   

** TODO Coulomb-potentials parameters

- [ ] Replace parameters with potential specific paramters, e.g. cellration for N^2 by N^2 cellratio etc. 
	  For this all occurences of these parameters must be found and changed. 

- [ ] The important files for that are solparallel_gui and solparallel_data. 


	  
