######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 29 09:54:33 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
